kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-port-controller
rules:
  - verbs:
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - services
---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: node-port-controller
  namespace: node-port-controller

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-port-controller
subjects:
  - kind: ServiceAccount
    name: node-port-controller
    namespace: node-port-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-port-controller
